### PR TITLE
Website template for  Catalyts 

### PR DESCRIPTION
**Pull request by Shrey-Mehra**
This is an basic Website template due to exams I don't get time to edit it's background and texts hope you guys understand

### CODE REVIEW

**Comment by Shrey-Mehra** [comment]
after exams I'll change it's background by any hackathon video or with some cool stuffs also change its tab and all

**Comment by Shrey-Mehra** [comment]
Here is the link for preview

https://shrey-mehra.github.io/India-24.github.io/

**Review by ansh3108 — CHANGES_REQUESTED** [review]
The template you chose is pretty good, however, the first step of organizing a hackathon is true hacker spirit. You shouldn't use any tools for creating a website or use readymade templates, Instead, you should create one from scratch and on your own. You can team up with your friends but the money will be divided between you and your partner.

**Comment by Shrey-Mehra** [comment]
thanks for the suggestions man but this template is also scratch for me because I'm going to change whole website.
I added template because it helps me to let me know how's it looking

**Comment by Shrey-Mehra** [comment]
will update you with update the website

**Comment by ansh3108** [comment]
I am sorry but I cannot accept Pull Requests that have used a readymade template, You have to create it all by yourself, from scratch!

**Comment by Shrey-Mehra** [comment]
https://cloud-6juq7f0b9-hack-club-bot.vercel.app/0catalyts_-_google_chrome_2024-03-13_19-43-49.mp4

I made a small change have a look on this

**Comment by ansh3108** [comment]
Accepting any Pull Request if the website is a readymade template is not possible.

**Comment by Shrey-Mehra** [comment]
ok thanks for letting me know. so i'm closing my pull request hope i'll help you guys in other work

**Comment by ansh3108** [comment]
> ok thanks for letting me know. so i'm closing my pull request hope i'll help you guys in other work

You can contribute later if you have created something according to the things I mentioned

**Comment by Shrey-Mehra** [comment]
Sure 😊

**Pull request closed without merging**
